//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pavilions_WS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int ID { get; set; }
        public int Tenant { get; set; }
        public int ShoppingCenter { get; set; }
        public int Staff { get; set; }
        public string Pavilion { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> StartRent { get; set; }
        public Nullable<System.DateTime> EndRent { get; set; }
    
        public virtual Pavilions Pavilions { get; set; }
        public virtual ShoppingCenters ShoppingCenters { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Tenantry Tenantry { get; set; }
    }
}
